import type { Recipe } from './types'

export const RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: '豚の生姜焼き',
    emoji: '🥩',
    time: 20,
    servings: 2,
    description: '甘辛タレが絡んだ定番の生姜焼き。ご飯が進みます。',
    ingredients: ['豚肉', '生姜', '醤油', 'みりん', '砂糖', 'サラダ油'],
    tags: ['和食', '肉料理', '定番'],
    steps: [
      '豚肉は食べやすい大きさに切る',
      '生姜をすりおろし、醤油・みりん・砂糖を混ぜてタレを作る',
      'フライパンにサラダ油を熱し、豚肉を中火で炒める',
      '火が通ったらタレを加えて絡めて完成',
    ],
  },
  {
    id: 'r2',
    title: '肉じゃが',
    emoji: '🥔',
    time: 35,
    servings: 4,
    description: '懐かしい家庭の味。じゃがいもがほっくりと仕上がります。',
    ingredients: ['豚肉', 'じゃがいも', '玉ねぎ', '醤油', 'みりん', '砂糖', 'だし'],
    tags: ['和食', '煮物', '定番'],
    steps: [
      '野菜と肉を一口大に切る',
      '鍋に油を熱して肉を炒め、野菜を加える',
      'だし・醤油・みりん・砂糖を加えて中火で煮る',
      '野菜が柔らかくなったら火を止めて味をなじませる',
    ],
  },
  {
    id: 'r3',
    title: 'カレーライス',
    emoji: '🍛',
    time: 45,
    servings: 4,
    description: '野菜たっぷりの家庭カレー。翌日はさらに美味しい。',
    ingredients: ['鶏肉', 'じゃがいも', '玉ねぎ', '人参', 'カレールー', 'サラダ油'],
    tags: ['カレー', '洋食', '定番'],
    steps: [
      '野菜と鶏肉を一口大に切る',
      '鍋に油を熱して鶏肉・玉ねぎを炒める',
      'じゃがいも・人参を加え、水を入れて煮る',
      '野菜が柔らかくなったらカレールーを溶かして完成',
    ],
  },
  {
    id: 'r4',
    title: '鶏の唐揚げ',
    emoji: '🍗',
    time: 30,
    servings: 3,
    description: 'カリッとジューシーな本格唐揚げ。お弁当にも最適。',
    ingredients: ['鶏肉', '醤油', 'にんにく', '生姜', '片栗粉', '揚げ油'],
    tags: ['和食', '揚げ物', '肉料理'],
    steps: [
      '鶏肉を一口大に切る',
      '醤油・すりおろしにんにく・生姜で15分漬け込む',
      '片栗粉をまぶして180℃の油で揚げる',
      'きつね色になったら取り出す',
    ],
  },
  {
    id: 'r5',
    title: '豚汁',
    emoji: '🍲',
    time: 25,
    servings: 4,
    description: '具だくさんで体が温まる豚汁。根菜の旨みが溶け出します。',
    ingredients: ['豚肉', '大根', '人参', 'こんにゃく', '味噌', 'だし', 'ごま油'],
    tags: ['和食', '汁物', '定番'],
    steps: [
      '大根・人参を短冊切りにし、こんにゃくをちぎる',
      '鍋にごま油を熱して豚肉を炒める',
      '野菜とこんにゃくを加えてだしを入れ煮る',
      '野菜が柔らかくなったら火を止めて味噌を溶く',
    ],
  },
  {
    id: 'r6',
    title: '麻婆豆腐',
    emoji: '🌶️',
    time: 20,
    servings: 3,
    description: 'ピリッと辛い四川風麻婆豆腐。ご飯がどんどん進みます。',
    ingredients: ['豆腐', '豚ひき肉', '豆板醤', 'にんにく', '生姜', '醤油', 'ごま油'],
    tags: ['中華', '豆腐料理'],
    steps: [
      '豆腐を一口大に切り、湯通しする',
      'フライパンにごま油を熱してにんにく・生姜・豆板醤を炒める',
      'ひき肉を加えて炒め、だし汁と調味料を加える',
      '豆腐を加えて弱火で煮て、水溶き片栗粉でとろみをつける',
    ],
  },
  {
    id: 'r7',
    title: '親子丼',
    emoji: '🍚',
    time: 15,
    servings: 2,
    description: '半熟たまごがとろける定番丼もの。短時間で作れます。',
    ingredients: ['鶏肉', '卵', '玉ねぎ', '醤油', 'みりん', 'だし', 'ご飯'],
    tags: ['和食', '丼もの', '定番'],
    steps: [
      '鶏肉を一口大に切り、玉ねぎを薄切りにする',
      '小鍋にだし・醤油・みりんを入れて煮立てる',
      '鶏肉・玉ねぎを加えて火が通るまで煮る',
      '溶き卵を回し入れ、半熟でご飯にのせる',
    ],
  },
  {
    id: 'r8',
    title: 'オムライス',
    emoji: '🍳',
    time: 25,
    servings: 2,
    description: 'ふわふわ卵に包まれたケチャップライス。子供も大好き。',
    ingredients: ['鶏肉', '玉ねぎ', 'ご飯', '卵', 'ケチャップ', 'バター'],
    tags: ['洋食', '卵料理', '定番'],
    steps: [
      '鶏肉と玉ねぎを炒め、ご飯を加えケチャップで味付けする',
      '溶き卵（1人2個）をバターで薄く焼く',
      'ケチャップライスを卵で包む',
      'お皿に盛り付けてケチャップをかける',
    ],
  },
  {
    id: 'r9',
    title: 'ハンバーグ',
    emoji: '🍔',
    time: 40,
    servings: 4,
    description: '肉汁溢れるジューシーなハンバーグ。デミグラスソースで。',
    ingredients: ['合いびき肉', '玉ねぎ', '卵', 'パン粉', '牛乳', 'ケチャップ', 'ウスターソース'],
    tags: ['洋食', '肉料理', '定番'],
    steps: [
      '玉ねぎをみじん切りにして炒め、冷ます',
      'ひき肉・玉ねぎ・卵・パン粉・牛乳を混ぜてこねる',
      '形を整えてフライパンで両面焼く',
      'ケチャップ・ウスターソースでソースを作りかける',
    ],
  },
  {
    id: 'r10',
    title: '野菜炒め',
    emoji: '🥬',
    time: 15,
    servings: 2,
    description: '旬の野菜をたっぷり使ったシンプルな炒め物。',
    ingredients: ['キャベツ', 'もやし', '人参', '豚肉', '醤油', 'ごま油'],
    tags: ['中華', '野菜料理', '簡単'],
    steps: [
      '野菜を食べやすい大きさに切る',
      'フライパンにごま油を熱して豚肉を炒める',
      '野菜を加えて強火でさっと炒める',
      '醤油で味を整えて完成',
    ],
  },
  {
    id: 'r11',
    title: '炒飯',
    emoji: '🍚',
    time: 15,
    servings: 2,
    description: 'パラパラに仕上げる本格的な炒飯。',
    ingredients: ['ご飯', '卵', '長ねぎ', '醤油', 'ごま油', 'サラダ油'],
    tags: ['中華', 'ご飯もの', '簡単'],
    steps: [
      '卵をご飯に絡めておく',
      'フライパンに油を熱し強火で卵ご飯を炒める',
      '長ねぎを加えて混ぜながら炒める',
      '醤油・ごま油で味を整えて完成',
    ],
  },
  {
    id: 'r12',
    title: '味噌汁',
    emoji: '🍵',
    time: 10,
    servings: 2,
    description: '具だくさんの基本の味噌汁。毎日の食卓に。',
    ingredients: ['豆腐', 'わかめ', '味噌', 'だし', '長ねぎ'],
    tags: ['和食', '汁物', '簡単'],
    steps: [
      'だしを火にかけて沸かす',
      '豆腐を一口大に切って加える',
      'わかめを加えて火が通ったら火を止める',
      '味噌を溶き、長ねぎを散らす',
    ],
  },
  {
    id: 'r13',
    title: 'トマトパスタ',
    emoji: '🍝',
    time: 25,
    servings: 2,
    description: 'フレッシュトマトとにんにくの香るシンプルパスタ。',
    ingredients: ['パスタ', 'トマト', 'にんにく', '玉ねぎ', 'オリーブオイル', '塩'],
    tags: ['洋食', 'パスタ', '簡単'],
    steps: [
      'パスタを塩茹でする',
      'にんにく・玉ねぎをオリーブオイルで炒める',
      'トマトを加えてソースを作る',
      'パスタとソースを和えて完成',
    ],
  },
  {
    id: 'r14',
    title: '餃子',
    emoji: '🥟',
    time: 40,
    servings: 3,
    description: 'パリパリの皮に肉汁が詰まった手作り餃子。',
    ingredients: ['豚ひき肉', 'にら', 'キャベツ', 'にんにく', '生姜', '醤油', '餃子の皮'],
    tags: ['中華', '肉料理'],
    steps: [
      'キャベツとにらをみじん切りにして塩で水気を絞る',
      'ひき肉・野菜・調味料を混ぜてタネを作る',
      '皮で包んでフライパンで焼く',
      '水を入れて蒸し焼きにしてパリッと仕上げる',
    ],
  },
  {
    id: 'r15',
    title: '天ぷら',
    emoji: '🍤',
    time: 30,
    servings: 2,
    description: 'サクサクの衣が自慢の天ぷら盛り合わせ。',
    ingredients: ['海老', 'さつまいも', 'なす', '薄力粉', '卵', '揚げ油'],
    tags: ['和食', '揚げ物'],
    steps: [
      '卵と冷水を合わせ薄力粉を加えてさっくり混ぜる',
      '材料に薄力粉をまぶしてから衣をつける',
      '170℃の油で揚げる',
      '天つゆと大根おろしで食べる',
    ],
  },
  {
    id: 'r16',
    title: '塩焼き（鮭）',
    emoji: '🐟',
    time: 15,
    servings: 2,
    description: 'シンプルな塩焼き。素材の旨みを引き出します。',
    ingredients: ['鮭', '塩'],
    tags: ['和食', '魚料理', '簡単'],
    steps: [
      '鮭に塩を振って10分置く',
      'キッチンペーパーで水気を拭く',
      'グリルまたはフライパンで両面焼く',
      'レモンを添えて完成',
    ],
  },
  {
    id: 'r17',
    title: '大根の煮物',
    emoji: '🥕',
    time: 40,
    servings: 4,
    description: 'だしが染み込んだほっこり大根の煮物。',
    ingredients: ['大根', '醤油', 'みりん', '砂糖', 'だし'],
    tags: ['和食', '煮物'],
    steps: [
      '大根を2cm厚の輪切りにして面取りし下茹でする',
      'だし・醤油・みりん・砂糖を合わせる',
      '大根と合わせ汁を鍋に入れて中火で煮る',
      '落とし蓋をして20分ほど煮含める',
    ],
  },
  {
    id: 'r18',
    title: '卵焼き',
    emoji: '🍳',
    time: 10,
    servings: 2,
    description: '甘くてふんわりな和風卵焼き。お弁当の定番。',
    ingredients: ['卵', '砂糖', '醤油', 'みりん', 'サラダ油'],
    tags: ['和食', '卵料理', '簡単'],
    steps: [
      '卵・砂糖・醤油・みりんを混ぜる',
      '卵焼き器に油を熱し卵液を少量流す',
      '半熟のうちに手前に巻きながら数回繰り返す',
      '巻きすで形を整えて冷ます',
    ],
  },
  {
    id: 'r19',
    title: 'ポテトサラダ',
    emoji: '🥗',
    time: 25,
    servings: 4,
    description: '定番のポテトサラダ。具材たっぷりで食べ応えあり。',
    ingredients: ['じゃがいも', '人参', '玉ねぎ', 'ハム', 'マヨネーズ', '塩'],
    tags: ['洋食', 'サラダ', '定番'],
    steps: [
      'じゃがいも・人参を茹でて潰す',
      '玉ねぎを薄切りにして塩揉みし水気を絞る',
      'ハムを細切りにする',
      '全ての材料とマヨネーズを混ぜて塩で味を整える',
    ],
  },
  {
    id: 'r20',
    title: '牛丼',
    emoji: '🥩',
    time: 20,
    servings: 2,
    description: '甘辛タレがじっくり染みた牛丼。簡単・時短で絶品。',
    ingredients: ['牛肉', '玉ねぎ', '醤油', 'みりん', '砂糖', 'だし', 'ご飯'],
    tags: ['和食', '丼もの'],
    steps: [
      '玉ねぎを薄切りにする',
      'だし・醤油・みりん・砂糖を鍋で煮立てる',
      '玉ねぎを加えて柔らかくなったら牛肉を加える',
      '火が通ったらご飯にのせて完成',
    ],
  },
  {
    id: 'r21',
    title: '豚バラ大根',
    emoji: '🥩',
    time: 30,
    servings: 3,
    description: '豚バラから出る旨みで大根がとろとろに。',
    ingredients: ['豚肉', '大根', '醤油', 'みりん', '砂糖', 'ごま油'],
    tags: ['和食', '煮物'],
    steps: [
      '大根を一口大に切り下茹でする',
      '豚バラを3cm幅に切る',
      '鍋にごま油を熱して豚肉を炒め大根を加える',
      '調味料と水を加えて落とし蓋で20分煮る',
    ],
  },
  {
    id: 'r22',
    title: 'ほうれん草のおひたし',
    emoji: '🥦',
    time: 10,
    servings: 2,
    description: 'シンプルで栄養満点。だしが染みた一品。',
    ingredients: ['ほうれん草', '醤油', 'だし', 'かつお節'],
    tags: ['和食', '副菜', '簡単'],
    steps: [
      'ほうれん草を塩茹でして冷水にさらす',
      '水気を絞って3cm幅に切る',
      'だしと醤油を合わせてほうれん草を和える',
      'かつお節をのせて完成',
    ],
  },
  {
    id: 'r23',
    title: 'みそラーメン',
    emoji: '🍜',
    time: 20,
    servings: 2,
    description: '濃厚みそスープのラーメン。野菜たっぷりで満足感あり。',
    ingredients: ['中華麺', 'もやし', 'コーン', '長ねぎ', '豚ひき肉', '味噌', 'ごま油'],
    tags: ['ラーメン', '麺類'],
    steps: [
      'ひき肉を炒め、味噌・ごま油・鶏がらスープで汁を作る',
      'もやし・コーンを炒める',
      '麺を茹でてスープを入れた丼へ',
      '野菜と長ねぎをのせて完成',
    ],
  },
  {
    id: 'r24',
    title: '鍋焼きうどん',
    emoji: '🍲',
    time: 20,
    servings: 2,
    description: '体が温まる鍋焼きうどん。卵を落として濃厚に。',
    ingredients: ['うどん', '鶏肉', '長ねぎ', '卵', 'だし', '醤油', 'みりん'],
    tags: ['和食', '麺類'],
    steps: [
      'だし・醤油・みりんでスープを作る',
      '鶏肉と長ねぎを加えて煮る',
      'うどんを加えて温める',
      '卵を割り入れて半熟にして完成',
    ],
  },
  {
    id: 'r25',
    title: 'チキンソテー',
    emoji: '🍗',
    time: 25,
    servings: 2,
    description: '皮がパリパリのチキンソテー。レモンを絞っておしゃれに。',
    ingredients: ['鶏肉', 'にんにく', 'バター', 'レモン', '塩', 'こしょう'],
    tags: ['洋食', '肉料理'],
    steps: [
      '鶏肉に塩・こしょうをしてにんにくを擦り込む',
      'フライパンで皮目から中火で焼く',
      '皮がパリッとしたら裏返しバターを加える',
      'レモンを添えて完成',
    ],
  },
]

// Mock receipt templates for OCR simulation
interface MockReceiptItem {
  name: string
  category: import('./types').IngredientCategory
  quantity: number
  unit: string
  expiryDays?: number
}

interface MockReceipt {
  storeName: string
  items: MockReceiptItem[]
}

export const MOCK_RECEIPTS: MockReceipt[] = [
  {
    storeName: 'スーパーまいにち',
    items: [
      { name: '豚肉', category: '肉類', quantity: 300, unit: 'g', expiryDays: 3 },
      { name: '玉ねぎ', category: '野菜', quantity: 3, unit: '個', expiryDays: 14 },
      { name: '人参', category: '野菜', quantity: 2, unit: '本', expiryDays: 14 },
      { name: 'キャベツ', category: '野菜', quantity: 1, unit: '個', expiryDays: 7 },
      { name: '醤油', category: '調味料', quantity: 1, unit: '本' },
    ],
  },
  {
    storeName: 'コープ',
    items: [
      { name: '鶏肉', category: '肉類', quantity: 400, unit: 'g', expiryDays: 2 },
      { name: '卵', category: '乳製品・卵', quantity: 10, unit: '個', expiryDays: 21 },
      { name: '牛乳', category: '乳製品・卵', quantity: 1, unit: 'L', expiryDays: 7 },
      { name: 'じゃがいも', category: '野菜', quantity: 5, unit: '個', expiryDays: 21 },
      { name: 'みりん', category: '調味料', quantity: 1, unit: '本' },
    ],
  },
  {
    storeName: 'イトーヨーカドー',
    items: [
      { name: '大根', category: '野菜', quantity: 1, unit: '本', expiryDays: 14 },
      { name: '豆腐', category: 'その他', quantity: 2, unit: '個', expiryDays: 5 },
      { name: 'ほうれん草', category: '野菜', quantity: 1, unit: '袋', expiryDays: 4 },
      { name: '合いびき肉', category: '肉類', quantity: 300, unit: 'g', expiryDays: 2 },
      { name: 'パスタ', category: '穀物・麺類', quantity: 1, unit: '袋' },
    ],
  },
  {
    storeName: 'ライフ',
    items: [
      { name: '鮭', category: '魚介類', quantity: 2, unit: '枚', expiryDays: 2 },
      { name: 'トマト', category: '野菜', quantity: 4, unit: '個', expiryDays: 5 },
      { name: '長ねぎ', category: '野菜', quantity: 2, unit: '本', expiryDays: 7 },
      { name: 'バター', category: '乳製品・卵', quantity: 1, unit: '個', expiryDays: 90 },
      { name: '生姜', category: '野菜', quantity: 1, unit: '個', expiryDays: 14 },
    ],
  },
]

export const SAMPLE_INVENTORY = [
  { name: '豚肉', category: '肉類' as const, quantity: 300, unit: 'g', expiryDays: 3 },
  { name: '玉ねぎ', category: '野菜' as const, quantity: 3, unit: '個', expiryDays: 7 },
  { name: '人参', category: '野菜' as const, quantity: 2, unit: '本', expiryDays: 5 },
  { name: '生姜', category: '野菜' as const, quantity: 1, unit: '個', expiryDays: 14 },
  { name: '卵', category: '乳製品・卵' as const, quantity: 8, unit: '個', expiryDays: 14 },
  { name: 'キャベツ', category: '野菜' as const, quantity: 1, unit: '個', expiryDays: 4 },
  { name: '醤油', category: '調味料' as const, quantity: 1, unit: '本' },
  { name: 'みりん', category: '調味料' as const, quantity: 1, unit: '本' },
  { name: '砂糖', category: '調味料' as const, quantity: 1, unit: '袋' },
  { name: 'サラダ油', category: '調味料' as const, quantity: 1, unit: '本' },
  { name: 'ご飯', category: '穀物・麺類' as const, quantity: 5, unit: '合' },
]
